-- SIPIC-RP — núcleo de dados isolado por prefixo sipic_
-- Projetado para coexistir com outros sistemas no mesmo projeto Supabase.

create extension if not exists pgcrypto;

create or replace function public.sipic_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.sipic_sectors (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  zone text not null,
  latitude double precision not null,
  longitude double precision not null,
  imperviousness numeric(5,4) not null default 0.5 check (imperviousness between 0 and 1),
  ndvi numeric(5,4) not null default 0.3 check (ndvi between -1 and 1),
  sky_view_factor numeric(5,4) not null default 0.6 check (sky_view_factor between 0 and 1),
  building_density numeric(5,4) not null default 0.5 check (building_density between 0 and 1),
  ventilation_factor numeric(5,4) not null default 0.5 check (ventilation_factor between 0 and 1),
  heat_offset_c numeric(6,3) not null default 0,
  is_reference boolean not null default false,
  geometry_geojson jsonb,
  metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sipic_stations (
  id uuid primary key default gen_random_uuid(),
  sector_id uuid references public.sipic_sectors(id) on delete set null,
  code text not null unique,
  name text not null,
  source text not null,
  station_type text not null default 'virtual_grid',
  latitude double precision not null,
  longitude double precision not null,
  status text not null default 'online' check (status in ('online','warning','offline','maintenance')),
  last_seen_at timestamptz,
  quality_score numeric(5,2) not null default 100 check (quality_score between 0 and 100),
  metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sipic_observations (
  id bigint generated by default as identity primary key,
  station_id uuid not null references public.sipic_stations(id) on delete cascade,
  observed_at timestamptz not null,
  ingested_at timestamptz not null default now(),
  source text not null,
  data_class text not null default 'observed' check (data_class in ('observed','calculated','modeled','simulated')),
  air_temperature_c numeric(7,3),
  apparent_temperature_c numeric(7,3),
  surface_temperature_c numeric(7,3),
  relative_humidity_pct numeric(7,3),
  surface_pressure_hpa numeric(9,3),
  wind_speed_ms numeric(7,3),
  wind_direction_deg numeric(7,3),
  shortwave_radiation_wm2 numeric(10,3),
  precipitation_mm numeric(9,3),
  weather_code integer,
  pm25_ugm3 numeric(9,3),
  pm10_ugm3 numeric(9,3),
  us_aqi numeric(8,3),
  ozone_ugm3 numeric(10,3),
  nitrogen_dioxide_ugm3 numeric(10,3),
  sulphur_dioxide_ugm3 numeric(10,3),
  carbon_monoxide_ugm3 numeric(12,3),
  uv_index numeric(7,3),
  ndvi numeric(6,4),
  urban_heat_island_c numeric(7,3),
  risk_score numeric(6,2),
  quality_score numeric(5,2) not null default 90 check (quality_score between 0 and 100),
  raw_payload jsonb not null default '{}'::jsonb,
  unique (station_id, observed_at, source)
);

create table if not exists public.sipic_predictions (
  id bigint generated by default as identity primary key,
  sector_id uuid not null references public.sipic_sectors(id) on delete cascade,
  generated_at timestamptz not null,
  valid_at timestamptz not null,
  horizon_hours integer not null check (horizon_hours >= 0),
  model_version text not null,
  source text not null default 'hybrid_open_meteo_morphology',
  air_temperature_c numeric(7,3),
  surface_temperature_c numeric(7,3),
  apparent_temperature_c numeric(7,3),
  urban_heat_island_c numeric(7,3),
  lower_bound_c numeric(7,3),
  upper_bound_c numeric(7,3),
  risk_score numeric(6,2),
  risk_level text check (risk_level in ('low','moderate','high','critical')),
  confidence_pct numeric(5,2) check (confidence_pct between 0 and 100),
  explanations jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (sector_id, generated_at, valid_at, model_version)
);

create table if not exists public.sipic_alerts (
  id uuid primary key default gen_random_uuid(),
  sector_id uuid references public.sipic_sectors(id) on delete cascade,
  fingerprint text not null unique,
  generated_at timestamptz not null default now(),
  valid_from timestamptz not null,
  valid_until timestamptz,
  alert_type text not null default 'thermal_risk',
  level text not null check (level in ('info','attention','warning','critical')),
  title text not null,
  message text not null,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sipic_ingestion_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running' check (status in ('running','success','partial','failed')),
  records_read integer not null default 0,
  records_written integer not null default 0,
  cache_hit boolean not null default false,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.sipic_api_cache (
  cache_key text primary key,
  source text not null,
  payload jsonb not null,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null,
  status text not null default 'fresh' check (status in ('fresh','stale','error')),
  error_message text,
  updated_at timestamptz not null default now()
);

create table if not exists public.sipic_reports (
  id uuid primary key default gen_random_uuid(),
  report_type text not null default 'operational_snapshot',
  generated_at timestamptz not null default now(),
  period_start timestamptz,
  period_end timestamptz,
  status text not null default 'ready' check (status in ('queued','processing','ready','failed')),
  payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sipic_settings (
  key text primary key,
  value jsonb not null,
  description text,
  public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sipic_observations_station_time_idx
  on public.sipic_observations (station_id, observed_at desc);
create index if not exists sipic_observations_time_idx
  on public.sipic_observations (observed_at desc);
create index if not exists sipic_predictions_sector_valid_idx
  on public.sipic_predictions (sector_id, valid_at desc);
create index if not exists sipic_predictions_generated_idx
  on public.sipic_predictions (generated_at desc);
create index if not exists sipic_alerts_active_idx
  on public.sipic_alerts (active, generated_at desc);
create index if not exists sipic_cache_expiry_idx
  on public.sipic_api_cache (expires_at);

create or replace trigger sipic_sectors_touch_updated_at
before update on public.sipic_sectors
for each row execute function public.sipic_touch_updated_at();

create or replace trigger sipic_stations_touch_updated_at
before update on public.sipic_stations
for each row execute function public.sipic_touch_updated_at();

create or replace trigger sipic_alerts_touch_updated_at
before update on public.sipic_alerts
for each row execute function public.sipic_touch_updated_at();

create or replace trigger sipic_cache_touch_updated_at
before update on public.sipic_api_cache
for each row execute function public.sipic_touch_updated_at();

create or replace trigger sipic_settings_touch_updated_at
before update on public.sipic_settings
for each row execute function public.sipic_touch_updated_at();

alter table public.sipic_sectors enable row level security;
alter table public.sipic_stations enable row level security;
alter table public.sipic_observations enable row level security;
alter table public.sipic_predictions enable row level security;
alter table public.sipic_alerts enable row level security;
alter table public.sipic_ingestion_runs enable row level security;
alter table public.sipic_api_cache enable row level security;
alter table public.sipic_reports enable row level security;
alter table public.sipic_settings enable row level security;

-- Leitura pública apenas do catálogo e dos resultados científicos publicados.
drop policy if exists sipic_public_read_sectors on public.sipic_sectors;
create policy sipic_public_read_sectors on public.sipic_sectors
for select to anon, authenticated using (active = true);

drop policy if exists sipic_public_read_stations on public.sipic_stations;
create policy sipic_public_read_stations on public.sipic_stations
for select to anon, authenticated using (active = true);

drop policy if exists sipic_public_read_observations on public.sipic_observations;
create policy sipic_public_read_observations on public.sipic_observations
for select to anon, authenticated using (observed_at >= now() - interval '30 days');

drop policy if exists sipic_public_read_predictions on public.sipic_predictions;
create policy sipic_public_read_predictions on public.sipic_predictions
for select to anon, authenticated using (valid_at >= now() - interval '2 days');

drop policy if exists sipic_public_read_alerts on public.sipic_alerts;
create policy sipic_public_read_alerts on public.sipic_alerts
for select to anon, authenticated using (active = true);

drop policy if exists sipic_public_read_settings on public.sipic_settings;
create policy sipic_public_read_settings on public.sipic_settings
for select to anon, authenticated using (public = true);

grant select on public.sipic_sectors, public.sipic_stations, public.sipic_observations,
  public.sipic_predictions, public.sipic_alerts, public.sipic_settings to anon, authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace view public.sipic_latest_observations
with (security_invoker = true)
as
select distinct on (o.station_id)
  o.*,
  s.code as station_code,
  s.name as station_name,
  s.sector_id
from public.sipic_observations o
join public.sipic_stations s on s.id = o.station_id
order by o.station_id, o.observed_at desc;

grant select on public.sipic_latest_observations to anon, authenticated;

create or replace view public.sipic_active_alerts
with (security_invoker = true)
as
select
  a.*,
  s.code as sector_code,
  s.name as sector_name
from public.sipic_alerts a
left join public.sipic_sectors s on s.id = a.sector_id
where a.active = true
  and (a.valid_until is null or a.valid_until >= now());

grant select on public.sipic_active_alerts to anon, authenticated;

insert into public.sipic_sectors
  (code, name, zone, latitude, longitude, imperviousness, ndvi, sky_view_factor,
   building_density, ventilation_factor, heat_offset_c, is_reference, metadata)
values
  ('RP-CENTRO-04', 'Centro / Quadrilátero Central', 'Centro', -21.1775, -47.8103, 0.91, 0.19, 0.34, 0.88, 0.24, 3.35, false,
   '{"coordinate_kind":"representative","description":"Setor urbano de alta densidade"}'::jsonb),
  ('RP-LESTE-02', 'Zona Leste / Distrito Industrial', 'Leste', -21.1480, -47.7650, 0.94, 0.16, 0.48, 0.72, 0.30, 3.60, false,
   '{"coordinate_kind":"representative","description":"Setor industrial com grandes superfícies impermeáveis"}'::jsonb),
  ('RP-NORTE-07', 'Campos Elíseos', 'Norte', -21.1600, -47.8000, 0.84, 0.24, 0.39, 0.81, 0.27, 2.85, false,
   '{"coordinate_kind":"representative"}'::jsonb),
  ('RP-OESTE-03', 'Zona Oeste / Ipiranga', 'Oeste', -21.1680, -47.8370, 0.73, 0.29, 0.52, 0.66, 0.42, 2.10, false,
   '{"coordinate_kind":"representative"}'::jsonb),
  ('RP-SUL-05', 'Zona Sul / Jardim Botânico', 'Sul', -21.2150, -47.7950, 0.54, 0.48, 0.66, 0.48, 0.61, 1.10, false,
   '{"coordinate_kind":"representative"}'::jsonb),
  ('RP-NORTE-01', 'Zona Norte / Quintino Facci', 'Norte', -21.1450, -47.8250, 0.69, 0.27, 0.58, 0.57, 0.44, 1.85, false,
   '{"coordinate_kind":"representative"}'::jsonb),
  ('RP-OESTE-09', 'Campus USP / Monte Alegre', 'Oeste', -21.1650, -47.8550, 0.31, 0.62, 0.77, 0.25, 0.73, 0.35, false,
   '{"coordinate_kind":"representative","description":"Referência urbana vegetada"}'::jsonb),
  ('RP-REF-01', 'Referência periurbana', 'Periurbano', -21.2400, -47.7200, 0.18, 0.68, 0.88, 0.12, 0.86, -0.70, true,
   '{"coordinate_kind":"representative","description":"Referência experimental periurbana"}'::jsonb)
on conflict (code) do update set
  name = excluded.name,
  zone = excluded.zone,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  imperviousness = excluded.imperviousness,
  ndvi = excluded.ndvi,
  sky_view_factor = excluded.sky_view_factor,
  building_density = excluded.building_density,
  ventilation_factor = excluded.ventilation_factor,
  heat_offset_c = excluded.heat_offset_c,
  is_reference = excluded.is_reference,
  metadata = excluded.metadata,
  active = true;

insert into public.sipic_stations
  (sector_id, code, name, source, station_type, latitude, longitude, status, quality_score, metadata)
select id, code, name || ' — grade virtual', 'SIPIC-RP', 'virtual_sector', latitude, longitude, 'online', 88,
       jsonb_build_object('model', 'Open-Meteo + correção morfológica', 'public', true)
from public.sipic_sectors
on conflict (code) do update set
  sector_id = excluded.sector_id,
  name = excluded.name,
  source = excluded.source,
  station_type = excluded.station_type,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  status = excluded.status,
  quality_score = excluded.quality_score,
  metadata = excluded.metadata,
  active = true;

insert into public.sipic_stations
  (code, name, source, station_type, latitude, longitude, status, quality_score, metadata)
values
  ('RP-OPENMETEO', 'Ribeirão Preto — Open-Meteo', 'Open-Meteo', 'external_model', -21.1775, -47.8103, 'online', 92,
   '{"variables":["temperatura","umidade","vento","pressão","radiação","previsão"]}'::jsonb),
  ('RP-AIR-CAMS', 'Ribeirão Preto — CAMS/Open-Meteo', 'CAMS via Open-Meteo', 'external_model', -21.1775, -47.8103, 'online', 82,
   '{"variables":["PM2.5","PM10","O3","NO2","CO","SO2","AQI"]}'::jsonb),
  ('RP-NASA-POWER', 'Ribeirão Preto — NASA POWER', 'NASA POWER', 'satellite_reanalysis', -21.1775, -47.8103, 'online', 90,
   '{"variables":["radiação solar","temperatura","umidade","vento","precipitação"]}'::jsonb)
on conflict (code) do update set
  name = excluded.name,
  source = excluded.source,
  station_type = excluded.station_type,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  status = excluded.status,
  quality_score = excluded.quality_score,
  metadata = excluded.metadata,
  active = true;

insert into public.sipic_settings (key, value, description, public)
values
  ('project', '{"name":"SIPIC-RP","city":"Ribeirão Preto","state":"SP","country":"Brasil","timezone":"America/Sao_Paulo","latitude":-21.1775,"longitude":-47.8103}'::jsonb,
   'Configuração geográfica principal do projeto.', true),
  ('model', '{"version":"sipic-hybrid-1.0.0","type":"híbrido físico-estatístico experimental","forecast_hours":48,"disclaimer":"Não substitui alertas meteorológicos oficiais."}'::jsonb,
   'Metadados do modelo preditivo.', true),
  ('venus_reference', '{"surface_temperature_c":464.0,"surface_pressure_bar":92.0,"co2_percent":96.5,"role":"analogia científica controlada"}'::jsonb,
   'Constantes didáticas utilizadas na comparação com Vênus.', true)
on conflict (key) do update set
  value = excluded.value,
  description = excluded.description,
  public = excluded.public;
